### ISSUE TITLE
Absolute humidity conversion documentation bug

### ISSUE THREAD

**Issue by Player3324** [Sensirion/linux-sgp30#1]
A small formatting issue in Documentation.txt turns part of the formula from `exp(17.62 * T/(243.12 + T))` into `exp(17.62 * T)/(243.12 + T)`, which is obviously incorrect.

I also noticed that the example in the data sheet is inaccurate, neither this approximating formula nor the more precise calculation at https://www.aqua-calc.com/calculate/humidity yield 11.8 g/m³. The result for the data sheet formula is ~11.48, which looks a lot like a missed digit typo, the calculator's ~11.52.

**Comment by abrauchli** [comment]
Hi @sfPlayer1 thanks for taking the time to report it. I've forwarded the issue to the datasheet folks. I'm happy to ACK a patch to LKML to fix the documentation issue upstream.
